# Generated by Django 3.1.6 on 2021-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
    ]
