# Generated by Django 3.1.6 on 2021-02-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesProvided',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_name',
            new_name='name',
        ),
    ]
