# Generated by Django 3.1.6 on 2021-02-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='gallery',
        ),
    ]
