# Generated by Django 3.1.6 on 2021-02-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210226_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
