# Generated by Django 3.1.6 on 2021-02-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
