# Generated by Django 3.1.6 on 2021-02-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210226_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherCode',
        ),
    ]
